
spring:
  datasource:
    password: password
    url: jdbc:h2:mem:serverdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: create 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
      show-sql: true